### ISSUE TITLE
Add support for Ozone diagnostics

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/PyGSI#27]

**Comment by aerorahul** [comment]
closed by #26

**Comment by CoryMartin-NOAA** [comment]
@aerorahul PR #26 adds YAML generation for ozone; but PyGSI needs classes added to it to support ozone diagnostic file input

**Comment by aerorahul** [comment]
got it @CoryMartin-NOAA

**Comment by kevindougherty-noaa** [comment]
This has been addressed in PR #28. Closed issue.
