### ISSUE TITLE
Small bug fixes for plot_diags.py

### ISSUE THREAD

**Issue by BenjaminBlake-NOAA** [NOAA-EMC/PyGSI#35]
While I was trying to create O-A histograms, I got an error when I tried to plot surface pressure (ps) related to the x-axis label.  'ps' was not recognized, and I noticed it wasn't defined in conv_xlabels.  I also discovered that 'o-a' wasn't an option for metadata['Diag Type'].  I think these changes to plot_diags.py should be considered:

Line 157-165:
    conv_xlabels = {'t': "Temperature (K)",
                    'q': "Specific Humidity (kg/kg)",
                    'sst': "Sea Surface Temperature (K)",
                    'pw': "Precipitable Water (mm)",
                    **'ps': "Pressure (hPa)",**
                    'tcp': "Pressure (hPa)",
                    'u': "Windspeed (m/s)",
                    'v': "Windspeed (m/s)",
                    'windspeed': "Windspeed (m/s)"
                   }

Line 172:
    elif metadata['Diag Type'] **in ['oma', 'o-a']**:

Thanks!

**Comment by kevindougherty-noaa** [comment]
This has been addressed in #38 and has been merged. Closing issue.
