### ISSUE TITLE
Fix diags.py get_lat_lon()

### ISSUE THREAD

**Issue by EdwardSafford-NOAA** [NOAA-EMC/PyGSI#62]
When I added binning by height I missed a needed update to diags.py get_lat_lon().  

The else block beginning at line 542 should have a check on the lvl_type variable and handle 'height' separately from the default value 'pressure'.  There is an example of correct handling of lvl_type within the same function at line 507.

**Comment by EdwardSafford-NOAA** [comment]
Discovered another problem.  Recent changes to the class Convention _read_obs() routine added retrieval of the Prep_QC_Mark from the conventional diag file.  Problem (as reported below) is that gps conventional data helpfully uses Setup_QC_Mark not Prep_QC_Mark.  I'll add that to my fix list.

```
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/Edward.Safford/noscrub/PyGSI/scripts/mp_plot_conv_diags.py", line 113, in <module>
    p.map(plotting, work)
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/PyGSI/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/scratch1/NCEPDEV/da/Kevin.Dougherty/anaconda3/envs/PyGSI/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: 'Prep_QC_Mark'
```
@XiujuanSu-NOAA please consider running the scripts/mp_plot_conv_diags.py as a general test after changing diags.py.

**Comment by EdwardSafford-NOAA** [comment]
Hit this problem immediately when I started work on this issue and am still nowhere as far as understanding why it's now a problem.  I had written a test driver to run the get_data() routine in pyGSI/diags.py but with Su's changes it now produces this error which I'm at a loss to understand:
```
File "test_driver.py", line 102, in plotting
    data = diag.get_data( diag_type, obsid=obsid,
  File "/scratch1/NCEPDEV/da/Edward.Safford/noscrub/PyGSI/pyGSI/diags.py", line 322, in get_data
    hght_idx = np.where((self.height > level_list[i]) & (
TypeError: '>' not supported between instances of 'MaskedArray' and 'str'
```

**Comment by CoryMartin-NOAA** [comment]
@EdwardSafford-NOAA can you print out both self.height and level_list[i]? Seems like one of them (level_list?) might be a string and not a float/int value?

**Comment by EdwardSafford-NOAA** [comment]
@CoryMartin-NOAA Looks like all I had to do was write up the problem and the answer became obvious.  Yes, level_list is somehow ending up as a string instead of an integer.  My driver script is reading the level list from the yaml file, like it's always done, but somehow the list values are remaining as strings.  I must have done something stupid along the way.  When I cast the level_list values to int() in the get_data() routine it works fine.  So I need to clean up the level_list before I send it into get_data().

**Comment by EdwardSafford-NOAA** [comment]
I'm ready to issue a PR on this but I'm running into problems I don't understand.  I committed my changes to my working branch (bug/diags_62) and pushed to origin.  Then I checked out my branch main and did a squash merge of bug/diags_62, and pushed to origin main.  When I try to issue a PR my main branch shows no file changes from upstream main.  My bug_diags_62 does show the changes I want so I guess I'll try to squash merge again?  Me and git, man.  Intuitive it is not.

**Comment by EdwardSafford-NOAA** [comment]
PR #66 merged, closing this issue.

**Comment by CoryMartin-NOAA** [comment]
technically PR #66 is not yet merged but will be soon :-)

**Comment by EdwardSafford-NOAA** [comment]
My bad, I got overly excited.
